name: CI Pipeline - SIMCI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci-frontend:
    name: Build Frontend Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies frontend
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  ci-backend:
    name: Build Backend NestJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies backend
        working-directory: backend
        run: npm ci

      - name: Build backend
        working-directory: backend
        run: npm run build
